2024-11-27 12:43:14 - ERROR - [domains_check_MT.py:44] - Request error for maps.google.com: HTTPConnectionPool(host='maps.google.com', port=80): Read timed out. (read timeout=1)
None
2024-11-27 12:43:15 - ERROR - [domains_check_MT.py:44] - Request error for goo.gl: HTTPSConnectionPool(host='developers.googleblog.com', port=443): Read timed out. (read timeout=1)
None
2024-11-27 12:43:15 - ERROR - [domains_check_MT.py:44] - Request error for apps.apple.com: HTTPSConnectionPool(host='www.apple.com', port=443): Read timed out. (read timeout=1)
None
2024-11-27 12:43:16 - ERROR - [domains_check_MT.py:44] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-11-27 12:43:16 - ERROR - [domains_check_MT.py:44] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000238D7CC4860>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-11-27 12:43:18 - ERROR - [domains_check_MT.py:44] - Request error for yahoo.com: HTTPSConnectionPool(host='www.yahoo.com', port=443): Read timed out.
None
2024-11-27 12:43:18 - ERROR - [domains_check_MT.py:44] - Request error for wixsite.com: HTTPConnectionPool(host='wixsite.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000238D7A8DD90>: Failed to resolve 'wixsite.com' ([Errno 11001] getaddrinfo failed)"))
None
2024-11-27 12:43:18 - ERROR - [domains_check_MT.py:44] - Request error for forbes.com: HTTPSConnectionPool(host='www.forbes.com', port=443): Read timed out. (read timeout=1)
None
2024-11-27 12:43:18 - ERROR - [domains_check_MT.py:44] - Request error for nginx.com: HTTPSConnectionPool(host='www.nginx.com', port=443): Read timed out. (read timeout=1)
None
2024-11-27 12:43:19 - ERROR - [domains_check_MT.py:44] - Request error for baidu.com: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-11-27 12:43:19 - ERROR - [domains_check_MT.py:44] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-11-27 12:43:20 - ERROR - [domains_check_MT.py:44] - Request error for macromedia.com: HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000238D7CA6E70>, 'Connection to macromedia.com timed out. (connect timeout=1)'))
None
2024-11-27 12:43:51 - ERROR - [domains_check_MT.py:44] - Request error for wixsite.com: HTTPConnectionPool(host='wixsite.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000238D7C68950>: Failed to resolve 'wixsite.com' ([Errno 11001] getaddrinfo failed)"))
None
2024-11-27 17:45:37 - ERROR - [domains_check_MT.py:44] - Request error for adobe.com: HTTPSConnectionPool(host='www.adobe.com', port=443): Read timed out. (read timeout=1)
None
2024-11-27 17:45:39 - ERROR - [domains_check_MT.py:44] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001FD1985D610>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-11-27 17:45:39 - ERROR - [domains_check_MT.py:44] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-11-27 17:45:40 - ERROR - [domains_check_MT.py:44] - Request error for t.me: HTTPSConnectionPool(host='telegram.org', port=443): Read timed out. (read timeout=1)
None
2024-11-27 17:45:40 - ERROR - [domains_check_MT.py:44] - Request error for wixsite.com: HTTPConnectionPool(host='wixsite.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001FD194A1CA0>: Failed to resolve 'wixsite.com' ([Errno 11001] getaddrinfo failed)"))
None
2024-11-27 17:45:42 - ERROR - [domains_check_MT.py:44] - Request error for qq.com: HTTPConnectionPool(host='qq.com', port=80): Read timed out. (read timeout=1)
None
2024-11-27 17:45:42 - ERROR - [domains_check_MT.py:44] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-11-27 17:45:44 - ERROR - [domains_check_MT.py:44] - Request error for www.ncbi.nlm.nih.gov: HTTPSConnectionPool(host='www.ncbi.nlm.nih.gov', port=443): Read timed out. (read timeout=1)
None
2024-11-27 17:45:48 - ERROR - [domains_check_MT.py:44] - Request error for macromedia.com: HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FD17D11430>, 'Connection to macromedia.com timed out. (connect timeout=1)'))
None
2024-11-27 18:45:04 - ERROR - [domains_check_MT.py:44] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002C67842D8B0>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-11-27 18:45:05 - ERROR - [domains_check_MT.py:44] - Request error for wixsite.com: HTTPConnectionPool(host='wixsite.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002C679451790>: Failed to resolve 'wixsite.com' ([Errno 11001] getaddrinfo failed)"))
None
2024-11-27 18:45:05 - ERROR - [domains_check_MT.py:44] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-11-27 18:45:06 - ERROR - [domains_check_MT.py:44] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-11-27 18:45:07 - ERROR - [domains_check_MT.py:44] - Request error for open.spotify.com: HTTPSConnectionPool(host='open.spotify.com', port=443): Read timed out. (read timeout=1)
None
2024-11-27 18:45:07 - ERROR - [domains_check_MT.py:44] - Request error for f5.com: HTTPSConnectionPool(host='www.f5.com', port=443): Read timed out. (read timeout=1)
None
2024-11-27 18:45:08 - ERROR - [domains_check_MT.py:44] - Request error for macromedia.com: HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002C6783DCFB0>, 'Connection to macromedia.com timed out. (connect timeout=1)'))
None
