2024-12-09 21:31:51 - ERROR - [domains_check_MT.py:44] - Request error for adobe.com: HTTPSConnectionPool(host='www.adobe.com', port=443): Read timed out. (read timeout=1)
None
2024-12-09 21:31:52 - ERROR - [domains_check_MT.py:44] - Request error for miit.gov.cn: HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000130DB0FE360>: Failed to resolve 'miit.gov.cn' ([Errno 11001] getaddrinfo failed)"))
None
2024-12-09 21:31:53 - ERROR - [domains_check_MT.py:44] - Request error for nih.gov: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
None
2024-12-09 21:31:54 - ERROR - [domains_check_MT.py:44] - Request error for youtube-nocookie.com: HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'youtube-nocookie.com'. (_ssl.c:1000)")))
None
2024-12-09 21:31:56 - ERROR - [domains_check_MT.py:44] - Request error for nginx.com: HTTPSConnectionPool(host='www.f5.com', port=443): Read timed out. (read timeout=1)
None
2024-12-09 21:31:56 - ERROR - [domains_check_MT.py:44] - Request error for f5.com: HTTPSConnectionPool(host='www.f5.com', port=443): Read timed out. (read timeout=1)
None
2024-12-09 21:31:56 - ERROR - [domains_check_MT.py:44] - Request error for macromedia.com: HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000130D99676B0>, 'Connection to macromedia.com timed out. (connect timeout=1)'))
None
